# Configuration for training Gold Atlas data
data:
  dataset: "../data/test_datasets/gold_atlas_train.json"
  data_dir: "../data/test_datasets/gold_atlas"
  slice_thickness: 5
  target_sequence: "ct"
  guidance_sequences:
    - "t1"
    - "t2"
  skull_strip: 0.0
  crop_to_brain_margin:
    - 0
    - 0
    - 0
  batch_size: 4  # * 8 GPUS, i.e. 24. Note the ~4x higher resolution
  random_slicing_direction: false
  img_size:
    - 480
    - 480
trainer:
  num_val_samples: 24
  val_cache_path: "../data/cache/gold_atlas/val_slices_24"
  weighting: "none"
  n_epochs: 20000